export const CANCEL_ORDER_DESCRIPTION = [
    'Cancel ONE exact Market order you made on the NFT marketplace, in a single call. One action covers both',
    'sides: a Cell listing you published with `cpu_list_cell` and a Cell offer you published with',
    '`cpu_make_cell_offer` are cancelled by the same input, because the side is a fact of the order rather than',
    'something you select. This is the land market — Cells traded as NFTs — and a Market order is not a resource',
    'Lot: ending one of those is `cpu_return_lot`, and this call never touches it.',
    "YOU PICK THE ORDER. Read `cpu_get_my_listings` or `cpu_get_my_offers` first and pass that order's exact",
    "`orderHash`. Only the wallet that made the order can cancel it: another wallet's order fails before anything",
    'is broadcast.',
    'The call performs the whole action itself: it prepares the cancellation, checks that the prepared transaction',
    'goes to the pinned marketplace protocol contract on this chain and that its bytes cancel exactly the order you',
    'named, then sends that one transaction and waits for its receipt.',
    "Success is proven, not assumed: the receipt must carry the protocol's own cancellation event for that exact",
    'order, naming your wallet as the maker, and the transaction must have been sent by your wallet. An order that',
    'merely stopped being active is NEVER reported as cancelled — it may have been filled or expired instead, so an',
    'order that is gone without that proof fails with `staleListing` or `staleOffer` and no other order is touched.',
    'Retrying is safe: a repeated call re-checks the transaction it already sent instead of cancelling again, and',
    'can never bind another order. At worst a retry spends gas on a transaction the protocol rejects.',
    'The result reports `status` (`completed`, or `already_completed` when the cancellation proved to be done',
    'already), the `orderHash` cancelled, whether it was a listing or an offer, and the `cancellationTxHash`.',
].join(' ');
