export const TRANSPORT_DESCRIPTION = [
    'Move a resource between cells along a waypoint chain of tokenIds, on-chain (needs a session —',
    '`cpu_authenticate` first). One atomic move: debits the source, pays the $CPU transit fee for every foreign',
    'Hub on the route (auto-approved once) plus gas, and escrows a time-delayed delivery. Source and target must',
    'be your own cells past their first completed reveal; the waypoints between them may be Virgin ground (no',
    'completed reveal, minted or not), cells of yours, or any cell with a finished Hub, foreign ones included.',
    'Each hop must be within radius(from)+radius(to)−1 grid steps, and radius is per cell: a plain cell reaches',
    'the move radius, a finished Hub the radius its own tier serves. Recommended flow:',
    '`cpu_route_network` (export the graph and plan over it) or `cpu_next_hops` (scout waypoints leg by leg) →',
    'chain them yourself → `cpu_quote_transport` (verify fee/ETA) →',
    '`cpu_transport`. Returns the',
    'deliveryId and arrival time; the goods credit to the target only after arrival, when you call',
    '`cpu_finalize_delivery` (`cpu_list_my_transports` shows what is ready). A route over only your own cells and',
    'open Virgin ground pays no fee.',
].join(' ');

export const ROUTE_NETWORK_DESCRIPTION = [
    'Export the route graph for ONE move you are planning (read-only, needs `from`, `towards`, `resourceId` and',
    '`amount`). It does NOT answer with the graph: it writes the graph to a uniquely named JSON file in the',
    'temporary directory and answers with the file path, the schema and snapshot versions, node and hop counts,',
    'whether the two ends are connected, ordered instructions, and a prefilled cpu_quote_transport call. Load the',
    'file with code and plan over it — never paste it into the conversation. USE IT WHEN you have a code runner;',
    'without one, plan leg by leg with the cheap cpu_next_hops instead.',
    'Both ends must be your own cells past their first completed reveal — a foreign Hub is passage, never an end',
    'of a shipment. Nodes are every cell a shipment may pass through: Virgin ground (no completed reveal, minted',
    'or not, `owner` null when nobody has minted it), your own cells, and any cell with a finished Hub, foreign',
    'ones included; only foreign land past its first reveal without a finished Hub is closed, and a belt of it',
    'wider than your reach is the WALL. Each node carries owner, Virgin/own/finished-Hub flags, its own reach',
    'radius and the exact per-unit transit fee for your cargo. Edges are the hops the contract accepts',
    '(radius(a)+radius(b)−1 grid steps, so a finished Hub tier reaches as far as its own catalog row serves).',
    'Only the component(s) your two ends sit in are exported; `connected: false` means no chain exists today —',
    'goods stop at the border until you bridge it with a border Hub (it still needs an eligible landing point',
    'within reach on the far side), land across, or a detour.',
    'Routing over the graph is YOUR job: pick the chain, then verify it with cpu_quote_transport before spending.',
].join(' ');

export const NEXT_HOPS_DESCRIPTION = [
    'Survey the legal next waypoints from a cell (read-only). Lists every eligible waypoint within one hop under',
    'the reach rule: hop ≤ radius(from)+radius(to)−1 grid steps. Eligible means Virgin ground (`isVirgin` — no',
    'completed reveal yet, minted or not, `owner` null when nobody has minted it), any cell you own, or any cell',
    'carrying a finished Hub, foreign ones included. Only foreign land past its first completed reveal without a',
    'finished Hub is closed — that, not open ground, is the WALL: a belt of foreign revealed cells wider than',
    'your reach stops cargo until a finished Hub reaches across. Waypoints are passage only: a shipment still',
    'starts and ends on your own revealed cells.',
    'Radius is per cell, never global: a plain cell (Virgin ground included) carries the move radius and each',
    'finished Hub tier carries the radius its own catalog row serves, so `reach` on the origin and on every',
    'candidate is what you add up. A Hub counts only once its construction',
    'finishes: until then it grants no hub reach and charges no fee, and a foreign one is no waypoint at all —',
    '`fromReady` says whether your own origin is still building, which is why its reach may be smaller than you',
    'expect. Empty `hops`',
    'means goods can only be hauled up to here. Facts per candidate: hop distance, owner, hub and Virgin flags,',
    '`ready` build state, the exact per-unit transit fee for your `resourceId` cargo (your own cells charge none,',
    'a Hub of your own on them included, and so does bare Virgin ground — but a foreign',
    'finished Hub charges its fee even on a cell with no completed',
    'reveal), and — with `towards` —',
    'the remaining grid distance (a compass, not a route). Planning is YOUR job: pick each hop yourself (cheap',
    'vs short vs whose hub you trust), chain them into `path`, and verify with cpu_quote_transport. To break a',
    'wall: build a border Hub (it still needs an eligible landing cell within reach on the far side), buy land',
    'across, or go around. Routing is refused until the whole map has loaded, so a missing row can never pass as',
    'open ground. WHEN: the cheap point check — call it right before each leg and after',
    'cpu_get_changes shows movement (hubs get demolished, fees change while goods travel); replan via',
    'cpu_route_network only when a local fix is impossible.',
].join(' ');
