export const ACCEPT_CELL_OFFER_DESCRIPTION = [
    'Sell ONE Cell you own by accepting ONE exact offer on the NFT marketplace, in a single call. This is the land',
    'market — Cells traded as NFTs for a configured currency — and it is entirely separate from `cpu_create_lot`,',
    'which sells RESOURCES for $CPU inside the game.',
    "YOU PICK THE OFFER AND THE CELL. Read `cpu_get_my_offers_received` first and pass that offer's exact",
    '`orderHash`. An offer for one exact Cell already names the Cell; a trait or collection offer bids for a SET of',
    'Cells, so you must also pass the `tokenId` you are willing to sell — the call fails before sending anything',
    'when a criteria offer is not given one.',
    'If the pinned offer has been filled, cancelled or expired, the call fails with ORDER_UNAVAILABLE and sells',
    'NOTHING — it never substitutes a different offer or a different Cell for you.',
    'The call performs the whole action itself: it prepares the acceptance, checks that the prepared work is still',
    'that exact offer and that exact Cell of yours, sends any collection approval the wallet still owes and waits',
    'for its receipt, then sends the one fulfilment transaction. There is nothing to confirm afterwards.',
    "Success is proven, not assumed: the receipt must carry the protocol's own fulfilment event for that exact",
    'order, the transaction must have been sent by your wallet, and the Cell must no longer be owned by you. A',
    'trait or collection offer may stay ACTIVE afterwards — it can still buy other Cells — and that is not a',
    'failure and never a second sale of the same Cell.',
    'Retrying is safe for your Cells: once ownership has moved, a repeat refuses before sending anything, and a',
    'repeat of a transaction already broadcast re-checks that transaction instead of selling again. At worst a',
    'retry spends gas on a transaction the protocol rejects.',
    'The result reports `status` (`completed`, or `already_completed` when the sale proved to be done already), the',
    '`orderHash` accepted, the Cell sold, the buyer, the amount and currency you are paid, and every transaction',
    'hash in `txHashes` in the order it was broadcast.',
].join(' ');
