export const MAKE_CELL_OFFER_DESCRIPTION = [
    'Bid on ONE exact Cell you do not own on the NFT marketplace, in a single call. This is the land market —',
    'Cells traded as NFTs for a configured ERC-20 currency — and it is entirely separate from `cpu_create_lot`,',
    'which sells RESOURCES for $CPU inside the game. What you publish here is a Cell offer: an off-chain signed',
    'Market order, not a Lot and never a Fill.',
    'The call performs the whole action itself: it checks that you are not about to duplicate an offer, reads your',
    'current order counter from the marketplace protocol contract, prepares the offer, sends any currency approval',
    'your wallet still owes and waits for each receipt, signs the offer locally, and publishes it. There is',
    'nothing to confirm afterwards.',
    '`amount` is what you bid, as a base-unit decimal integer STRING (never a number), in the currency the',
    'marketplace configures for this collection — the result reports that currency with its symbol and decimals.',
    'You never pass the currency or the protocol counter: the currency comes from the marketplace configuration',
    'and the counter is read from the marketplace protocol contract.',
    'The offer is always an item offer for the one exact Cell you name; this tool never creates trait or',
    'collection offers. Your currency approval is for exactly the amount you bid, never an open-ended allowance.',
    'Retrying is safe: an identical repeated call resumes the same prepared offer instead of publishing a second',
    'one, and an equivalent offer of yours that is already active is returned with `already_completed` rather',
    'than duplicated.',
    'The result reports `status` (`completed`, or `already_completed`), the published offer with its `orderHash`,',
    'the currency, and every approval transaction hash in the order it was broadcast.',
].join(' ');
