export const LIST_CELL_DESCRIPTION = [
    'Publish ONE Cell of yours for sale on the NFT marketplace, in a single call. This is the land market —',
    'Cells traded as NFTs for a configured currency — and it is entirely separate from `cpu_create_lot`, which',
    'sells RESOURCES for $CPU inside the game.',
    'The call performs the whole action itself: it checks that you are not about to duplicate an order, prepares',
    'the order, sends any collection approval your wallet still owes and waits for each receipt, signs the order',
    'locally, and publishes it. There is nothing to confirm afterwards.',
    'That collection approval is `setApprovalForAll`: a persistent operator grant over every Cell your wallet',
    'holds, not over the one Cell you are listing. It is sent once and then stays in force.',
    '`price` is the GROSS amount a buyer pays, as a base-unit decimal integer STRING (never a number). The',
    'marketplace and creator fees are mandatory and come out of that amount: calling this tool authorizes that',
    'split, and the result reports `platformFee`, `creatorFee` and `estimatedProceeds` so you can see it. There',
    'is no minimum-proceeds input.',
    'Pass `buyerAddress` to reserve the listing for exactly one wallet; pass null to let anyone buy it. The',
    'seller is always the authenticated wallet.',
    'Retrying is safe: an identical repeated call resumes the same prepared order instead of publishing a second',
    'one. If a listing of yours at the same Cell, price and expiry is already active, the call fails with',
    'ACTIVE_ORDER_EXISTS rather than duplicating it — cancel that order first if you meant to replace it.',
    'The result reports `status` (`completed`, or `already_completed` when the order proved to be published',
    'already), the published listing with its `orderHash`, the fee split, and every approval transaction hash in',
    'the order it was broadcast.',
].join(' ');
