export const SERVER_INSTRUCTIONS = [
    'MCP server for Project CPU (blockchain game on EVM).',
    'Load your operating brief with `cpu_persona` before any other tool; every other tool refuses until you do.',
    'Authenticate first: `cpu_authenticate` opens a session — the default Paybox mode starts browser OAuth,',
    'EVM mode signs in via SIWE locally, and AGW mode starts a Device Authorization flow.',
    'Then read the entry point once: `cpu_get_game_config` carries the static rulebook — resources,',
    'buildings, costs, storage and transport parameters, contract addresses.',
    'It is a router, not the whole catalog: static facts plus a building index, and it names the tool to ask',
    'next — `cpu_get_building`, `cpu_find_buildings`, `cpu_get_resource`, `cpu_list_recipes`.',
    'The world is a finite sphere of land cells identified only by tokenId; there are no coordinates,',
    'adjacency comes from the `neighbors` list on each cell, and you plan routes yourself.',
    'Route planning loop: PLAN once with `cpu_route_network`, which writes the route graph for one move to a',
    'file for you to load with code, EXECUTE leg by leg re-checking your position with the cheap',
    '`cpu_next_hops` because the world moves while goods travel, VERIFY every chain with',
    '`cpu_quote_transport` before spending. Open ground with no completed reveal is passage; foreign land past',
    'its first reveal and carrying no finished hub is a wall. A shipment still starts and ends on your own',
    'revealed cells.',
    'You see the world only when you call a tool — there is no push.',
    'Trading on a hub you do not own is revocable: its owner can end your lot with `cpu_evict_lot`, and an',
    'Evicted lot sells to nobody until you bring that one lot home yourself with a Lot return',
    '(`cpu_quote_lot_return`, then `cpu_return_lot`, one lot and one route at a time).',
    'Every other mechanic — reveal, building, mining, crafting, transport, trade, syndicates, payouts —',
    'is carried by the tools themselves: read the description of the tool and call it rather than',
    'assuming the rules.',
].join(' ');

export const SENTENCE_BOUNDARY = /(?<=\.)\s+/u;
