export const SERVER_INSTRUCTIONS = [
    'MCP server for Project CPU (blockchain game on EVM).',
    'Load your operating brief with `cpu_persona` before any other tool; every other tool refuses until you do.',
    'Authenticate first: `cpu_authenticate` signs in via SIWE with the private key the server was started with.',
    'Then read `cpu_get_game_config` once: the static rulebook — resources, buildings, costs, storage and',
    'transport parameters, contract addresses — and a router naming the tool to ask next: `cpu_get_building`,',
    '`cpu_find_buildings`, `cpu_get_resource`, `cpu_list_recipes`.',
    "The world is a finite sphere of land cells identified only by tokenId; adjacency comes from each cell's",
    '`neighbors` list, and you plan routes yourself.',
    'Route planning loop: PLAN once with `cpu_route_network`, which writes the route graph for one move to a',
    'file you load with code, EXECUTE leg by leg re-checking your position with the cheap `cpu_next_hops`,',
    'VERIFY every chain with `cpu_quote_transport` before spending. Open ground with no completed reveal is',
    'passage; foreign land past its first reveal without a finished hub is a wall. A shipment starts and ends',
    'on revealed cells you own.',
    'You see the world only when you call a tool — there is no push.',
    'A lot on a hub you do not own can be ended by its owner (`cpu_evict_lot`); an Evicted lot sells to nobody',
    'until a Lot return brings it home (`cpu_quote_lot_return`, `cpu_return_lot`).',
    'Two markets, never blurred: resources sell inside the game as Lots bought in Fills; land sells outside it',
    '— a Cell is an NFT, and what you publish for it is a Market order (a Cell listing or a Cell offer) settled',
    'by Market fulfilment.',
    'Read the land market with `cpu_get_cell_market`; its five actions each carry the whole intent — prepare,',
    'approve, sign, send, verify — and act only on the exact `orderHash` you name.',
    'Every other mechanic — reveal, building, mining, crafting, transport, trade, syndicates, payouts —',
    "is carried by the tools themselves: read a tool's description and call it rather than assuming the rules.",
].join(' ');

export const SENTENCE_BOUNDARY = /(?<=\.)\s+/u;
